# Solar Forecast ML Integration - Services

force_retrain:
  name: Retrain ML Model
  description: >
    Forces immediate retraining of the Machine Learning model using all available historical data.
    Useful after significant data changes or to manually trigger an update.
  fields: {} # No fields required

reset_model:
  name: Reset ML Model
  description: >
    Resets the Machine Learning model to its initial state.
    WARNING: This deletes all learned weights and requires the model to retrain from scratch.
    Use with caution.
  fields: {} # No fields required

# Removed services (not implemented or handled differently):
# install_dependencies: (Handled via UI button/HA core)
# check_dependencies: (Handled via diagnostic sensors/logs)
# clear_history: (Can be done by deleting the prediction_history.json file manually if needed)
# manual_forecast: (Handled via UI button)